name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn package --batch-mode -Pnative -Dquarkus.native.container-build=true \
                                            -Dquarkus.container-image.build=true \
                                            -Dquarkus.container-image.push=true \
                                            -Dquarkus.container-image.registry=registry.hub.docker.com \
                                            -Dquarkus.jib.base-registry-username=${{ github.actor }} \
                                            -Dquarkus.jib.base-registry-password=${{ secrets.GITHUB_TOKEN }}
                                            -Dquarkus.container-image.registry=docker.pkg.github.com \
                                            -Dquarkus.container-image.group=github.repository
          